/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Purchase } from "./Purchase";
import { PurchaseCountArgs } from "./PurchaseCountArgs";
import { PurchaseFindManyArgs } from "./PurchaseFindManyArgs";
import { PurchaseFindUniqueArgs } from "./PurchaseFindUniqueArgs";
import { CreatePurchaseArgs } from "./CreatePurchaseArgs";
import { UpdatePurchaseArgs } from "./UpdatePurchaseArgs";
import { DeletePurchaseArgs } from "./DeletePurchaseArgs";
import { Asset } from "../../asset/base/Asset";
import { User } from "../../user/base/User";
import { PurchaseService } from "../purchase.service";
@graphql.Resolver(() => Purchase)
export class PurchaseResolverBase {
  constructor(protected readonly service: PurchaseService) {}

  async _purchasesMeta(
    @graphql.Args() args: PurchaseCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Purchase])
  async purchases(
    @graphql.Args() args: PurchaseFindManyArgs
  ): Promise<Purchase[]> {
    return this.service.purchases(args);
  }

  @graphql.Query(() => Purchase, { nullable: true })
  async purchase(
    @graphql.Args() args: PurchaseFindUniqueArgs
  ): Promise<Purchase | null> {
    const result = await this.service.purchase(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Purchase)
  async createPurchase(
    @graphql.Args() args: CreatePurchaseArgs
  ): Promise<Purchase> {
    return await this.service.createPurchase({
      ...args,
      data: {
        ...args.data,

        asset: args.data.asset
          ? {
              connect: args.data.asset,
            }
          : undefined,

        user: args.data.user
          ? {
              connect: args.data.user,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => Purchase)
  async updatePurchase(
    @graphql.Args() args: UpdatePurchaseArgs
  ): Promise<Purchase | null> {
    try {
      return await this.service.updatePurchase({
        ...args,
        data: {
          ...args.data,

          asset: args.data.asset
            ? {
                connect: args.data.asset,
              }
            : undefined,

          user: args.data.user
            ? {
                connect: args.data.user,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Purchase)
  async deletePurchase(
    @graphql.Args() args: DeletePurchaseArgs
  ): Promise<Purchase | null> {
    try {
      return await this.service.deletePurchase(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => Asset, {
    nullable: true,
    name: "asset",
  })
  async getAsset(@graphql.Parent() parent: Purchase): Promise<Asset | null> {
    const result = await this.service.getAsset(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @graphql.ResolveField(() => User, {
    nullable: true,
    name: "user",
  })
  async getUser(@graphql.Parent() parent: Purchase): Promise<User | null> {
    const result = await this.service.getUser(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
