/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Point } from "./Point";
import { PointCountArgs } from "./PointCountArgs";
import { PointFindManyArgs } from "./PointFindManyArgs";
import { PointFindUniqueArgs } from "./PointFindUniqueArgs";
import { CreatePointArgs } from "./CreatePointArgs";
import { UpdatePointArgs } from "./UpdatePointArgs";
import { DeletePointArgs } from "./DeletePointArgs";
import { User } from "../../user/base/User";
import { PointService } from "../point.service";
@graphql.Resolver(() => Point)
export class PointResolverBase {
  constructor(protected readonly service: PointService) {}

  async _pointsMeta(
    @graphql.Args() args: PointCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Point])
  async points(@graphql.Args() args: PointFindManyArgs): Promise<Point[]> {
    return this.service.points(args);
  }

  @graphql.Query(() => Point, { nullable: true })
  async point(
    @graphql.Args() args: PointFindUniqueArgs
  ): Promise<Point | null> {
    const result = await this.service.point(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Point)
  async createPoint(@graphql.Args() args: CreatePointArgs): Promise<Point> {
    return await this.service.createPoint({
      ...args,
      data: {
        ...args.data,

        user: args.data.user
          ? {
              connect: args.data.user,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => Point)
  async updatePoint(
    @graphql.Args() args: UpdatePointArgs
  ): Promise<Point | null> {
    try {
      return await this.service.updatePoint({
        ...args,
        data: {
          ...args.data,

          user: args.data.user
            ? {
                connect: args.data.user,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Point)
  async deletePoint(
    @graphql.Args() args: DeletePointArgs
  ): Promise<Point | null> {
    try {
      return await this.service.deletePoint(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => User, {
    nullable: true,
    name: "user",
  })
  async getUser(@graphql.Parent() parent: Point): Promise<User | null> {
    const result = await this.service.getUser(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
