/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import {
  Prisma,
  Point as PrismaPoint,
  User as PrismaUser,
} from "@prisma/client";

export class PointServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(args: Omit<Prisma.PointCountArgs, "select">): Promise<number> {
    return this.prisma.point.count(args);
  }

  async points(args: Prisma.PointFindManyArgs): Promise<PrismaPoint[]> {
    return this.prisma.point.findMany(args);
  }
  async point(args: Prisma.PointFindUniqueArgs): Promise<PrismaPoint | null> {
    return this.prisma.point.findUnique(args);
  }
  async createPoint(args: Prisma.PointCreateArgs): Promise<PrismaPoint> {
    return this.prisma.point.create(args);
  }
  async updatePoint(args: Prisma.PointUpdateArgs): Promise<PrismaPoint> {
    return this.prisma.point.update(args);
  }
  async deletePoint(args: Prisma.PointDeleteArgs): Promise<PrismaPoint> {
    return this.prisma.point.delete(args);
  }

  async getUser(parentId: string): Promise<PrismaUser | null> {
    return this.prisma.point
      .findUnique({
        where: { id: parentId },
      })
      .user();
  }
}
