/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { PointService } from "../point.service";
import { PointCreateInput } from "./PointCreateInput";
import { Point } from "./Point";
import { PointFindManyArgs } from "./PointFindManyArgs";
import { PointWhereUniqueInput } from "./PointWhereUniqueInput";
import { PointUpdateInput } from "./PointUpdateInput";

export class PointControllerBase {
  constructor(protected readonly service: PointService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Point })
  async createPoint(@common.Body() data: PointCreateInput): Promise<Point> {
    return await this.service.createPoint({
      data: {
        ...data,

        user: data.user
          ? {
              connect: data.user,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        description: true,
        id: true,
        origin: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },

        value: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Point] })
  @ApiNestedQuery(PointFindManyArgs)
  async points(@common.Req() request: Request): Promise<Point[]> {
    const args = plainToClass(PointFindManyArgs, request.query);
    return this.service.points({
      ...args,
      select: {
        createdAt: true,
        description: true,
        id: true,
        origin: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },

        value: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Point })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async point(
    @common.Param() params: PointWhereUniqueInput
  ): Promise<Point | null> {
    const result = await this.service.point({
      where: params,
      select: {
        createdAt: true,
        description: true,
        id: true,
        origin: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },

        value: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Point })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updatePoint(
    @common.Param() params: PointWhereUniqueInput,
    @common.Body() data: PointUpdateInput
  ): Promise<Point | null> {
    try {
      return await this.service.updatePoint({
        where: params,
        data: {
          ...data,

          user: data.user
            ? {
                connect: data.user,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          description: true,
          id: true,
          origin: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },

          value: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Point })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deletePoint(
    @common.Param() params: PointWhereUniqueInput
  ): Promise<Point | null> {
    try {
      return await this.service.deletePoint({
        where: params,
        select: {
          createdAt: true,
          description: true,
          id: true,
          origin: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },

          value: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
